### ISSUE TITLE
Change form header to match design, + alignment & space

### ISSUE THREAD

**Issue by thoell** [knowit/kompetansekartlegging-gui#253]
Desired design:

![image](https://user-images.githubusercontent.com/73111792/107039262-ee559c80-67bd-11eb-83ed-d1a5116cad6b.png)

Current:

![image](https://user-images.githubusercontent.com/73111792/107039289-fad9f500-67bd-11eb-88d6-763289c63b09.png)

**Comment by awgaan** [comment]
@thoell Hva blei vi enige om her?
Gi progressbaren mer space? Og aligne tittelen?

**Comment by thoell** [comment]
> @thoell Hva blei vi enige om her?
> Gi progressbaren mer space? Og aligne tittelen?

Progress bar øverst, tittel under, litt tydeligere progress bar, i alle fall noe større tekst. Både tittel og progress bar skal være i et freeze pane.

**Comment by awgaan** [comment]
These changes should only be done for desktop?

**Comment by thoell** [comment]
Jepp! Bare desktop. =)
